django/proyectos/bymecoffe_base/src/bymecoffe_django/bymecoffe/apps/core/urls.py
from django.urls import path, include

from django.contrib.auth import views as auth_views


from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', views.login, name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'), # validar
]

django/proyectos/bymecoffe_base/src/bymecoffe_django/bymecoffe/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('bymecoffe.apps.core.urls', namespace='core')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', RedirectView.as_view(url='core/'), name='index'),
]

django/proyectos/bymecoffe_base/src/bymecoffe_django/bymecoffe/apps/core/models.py
from django.db import models

# Create your models here.

django/proyectos/bymecoffe_base/src/bymecoffe_django/bymecoffe/apps/core/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request, 'core/index.html')

def login(request):
    return render(request, 'core/login.html')

@login_required
def home(request):
    return render(request, 'core/home.html')

django/proyectos/bymecoffe_base/src/bymecoffe_django/bymecoffe/apps/core/templates/base.html
<!-- templates/base.html -->

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <title>Social Auth with Django</title>
</head>
<body>
    <div class="container-fluid">
        <div>
            <h1 class="text-white text-center">{% block title %}{% endblock %}</h1>
            <div class="card p-5">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

django/proyectos/bymecoffe_base/src/bymecoffe_django/bymecoffe/apps/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}" />
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container-fluid">
        <div>
            <h1 class="text-white text-center">{% block header %}{% endblock %}</h1>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

django/proyectos/bymecoffe_base/src/bymecoffe_django/bymecoffe/apps/core/templates/core/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block header %} Login Test {% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12 mb-3">
        <h4 class="text-center"> Welcome {{ user.username }} </h4>
    </div>
</div>
{% endblock %}

django/proyectos/bymecoffe_base/src/bymecoffe_django/bymecoffe/apps/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %} Inicio {% endblock %}
{% block header %} Login Test {% endblock %}

{% block content %}
<section class="d-flex flex-column">
    <h4 class="text-white text-center"> INICIO </h4>
    <button type="button" class="btn btn-primary">
        <a href="{% url 'core:login' %}">ir a autenticarme</a>
    </button>
</section>
{% endblock %}

django/proyectos/bymecoffe_base/src/bymecoffe_django/bymecoffe/apps/core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %} Login {% endblock %}
{% block header %} Login Test {% endblock %}

{% block content %}
<section class="d-flex flex-column">
    <h4 class="text-white text-center"> LOGIN </h4>
    <button class="btn btn-danger  mb-2">
        <a href="#">Login with Instagram</a>
    </button>
    <button class="btn btn-primary mb-2">
        <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
    </button>
    <button class="btn btn-info mb-2">
        <a href="#">Login with LinkedIn</a>
    </button>
</section>
{% endblock %}